[package]
name = "simple-prolog"
version = "0.1.0"
edition = "2024"

[dependencies]
chumsky = "0.11.1"
eframe = "0.28"
egui = "0.28"
regex = "1.10"
serde = { version = "1.0.228", features = ["derive"] }
